title: "My Knowledge Articles"
description: "A collection of how-to guides and technical tutorials"
baseurl: ""  # Leave blank for GitHub Pages
url: "https://yourusername.github.io"  # Replace with your GitHub Pages URL

theme: slate

# Enable syntax highlighting for code blocks
highlighter: rouge

# Enable search on the site (you may need to add a search plugin)
plugins:
  - jekyll-seo-tag

# Enable Table of Contents (TOC) for Markdown content
markdown: kramdown
kramdown:
  toc: true  # Enables automatic TOC generation
  toc_levels: 1..3  # Defines which heading levels to include in the TOC (1 to 3)
  syntax_highlighter: rouge

# Customize navigation for pages and posts
navigation:
  - title: "Home"
    url: "/"
  - title: "Getting Started"
    url: "/getting-started/"
  - title: "Tutorials"
    url: "/tutorials/"

# Optional: Enable Google Analytics
# google_analytics: UA-XXXXX-X

# Other configurations like social media links or footer content
social_links:
  github: "https://github.com/yourusername"
  twitter: "https://twitter.com/yourusername"
