title: "AWS DevOps Tutorials"
description: "A collection of lessons and demos for AWS DevOps"
baseurl: ""  # Leave empty for GitHub Pages
url: "https://yourusername.github.io/aws-devops"  # Replace with your GitHub Pages URL

remote_theme: pages-themes/slate

markdown: kramdown
kramdown:
  toc: true
  toc_levels: 1..3
  syntax_highlighter: rouge

navigation:
  - title: "Home"
    url: "/"
  - title: "Lesson 1"
    url: "/lesson1/"
  - title: "Lesson 2"
    url: "/lesson2/"
