# _config.yml
title: AWS DevOps Demos
description: A collection of demos organized by lessons
theme: jekyll-theme-minimal
url: https://jvsocial.github.io/aws-devops
baseurl: "/aws-devops"
author: jvsocial

# Enable collections for demos
collections:
  demos:
    output: true
    permalink: /demos/:title/
