title: AWS DevOps Demos
description: A collection of demos organized by lessons
theme: jekyll-theme-minimal
url: https://jvsocial.github.io/aws-devops
baseurl: "/jekyll"
author: jvsocial


# Plugins and features
plugins:
  - jekyll-readme-index
