# _config.yml
title: My Demos Site
description: A collection of demos organized by lessons
theme: jekyll-theme-minimal
url: https://jvsocial.github.io/aws-devops
baseurl: "/aws-devops"
author: jvsocial

# Enable collections for demos
collections:
  demos:
    output: true
    permalink: /:path/
