title: "AWS DevOps Tutorials"
description: "A collection of lessons and demos for AWS DevOps"
baseurl: "/aws-devops"  # The base URL for your GitHub Pages site
url: "https://jvsocial.github.io"  # The root URL of your GitHub Pages site

remote_theme: pages-themes/slate

markdown: kramdown
kramdown:
  toc: true
  toc_levels: 1..3
  syntax_highlighter: rouge

navigation:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "Lesson 1"
    url: "{{ site.baseurl }}/lesson1/"
  - title: "Lesson 2"
    url: "{{ site.baseurl }}/lesson2/"
