# _config.yml
title: Documentation Hub
description: Knowledge Base Documentation
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md

# Collections settings for dynamic folder structure
collections_dir: docs
collections:
  pages:
    output: true
    permalink: /:path/

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "*/index.md"
    values:
      layout: "section"